### ISSUE TITLE
keyboard fn key doesn't function

### ISSUE THREAD

**Issue by ghost** [getchip/PocketCHIP-Docs#6]
According to your doc, pressing fn-j should produce a > (greater than) sign. Mine does not. Nor can I print any character such as : (colon) or anything else the fn key is supposed to print. So using Vi is out. Am I the only one??

**Comment by nyboer** [comment]
That is correct. This probably isn't the best place for this question though, since it's not directly related to the veracity or function of the documentation website. Our forums have some helpful tips:
https://bbs.nextthing.co/search?q=fn%20key
